<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-04-07 10:19
=======
# Generated by Django 3.2.12 on 2022-04-07 10:18
>>>>>>> f647e94195259fc71d0bd6f36977d6d8a7864d1e

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import django.utils.timezone
=======
>>>>>>> f647e94195259fc71d0bd6f36977d6d8a7864d1e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
=======
>>>>>>> f647e94195259fc71d0bd6f36977d6d8a7864d1e
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
